# Generated by Django 6.0.4 on 2026-04-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_server_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='uptime_seconds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_cores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='kernel_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='os_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='total_disk_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='total_ram_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
