# Generated by Django 6.0.4 on 2026-04-26 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_metric_uptime_seconds_server_cpu_cores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_alert_threshold_percent',
            field=models.PositiveSmallIntegerField(default=85),
        ),
        migrations.AddField(
            model_name='server',
            name='metric_retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='server',
            name='notify_on_high_cpu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='notify_on_high_ram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='notify_on_offline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_alert_threshold_percent',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_refresh_interval_seconds', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
