# Generated by Django 6.0.4 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_server_cpu_alert_threshold_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='data_refresh_interval_seconds',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
