# Generated by Django 6.0.4 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usersettings_default_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
